### ISSUE TITLE
here's the code

### ISSUE THREAD

**Issue by rexo6565** [simonfarah/tiktok-bot#111]
Traceback (most recent call last):                                           
  File "/home/rexxxo/tiktok-bot/bot.py", line 205, in <module>
    bot.start()
  File "/home/rexxxo/tiktok-bot/bot.py", line 103, in start
    self.select_service(choice)
  File "/home/rexxxo/tiktok-bot/bot.py", line 115, in select_service
    self.start_service(div, video_url)
  File "/home/rexxxo/tiktok-bot/bot.py", line 139, in start_service
    remaining_time = self.check_remaining_time(div)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/tiktok-bot/bot.py", line 150, in check_remaining_time
    text = element.text
           ^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=123.0.6312.86); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5613f4516873 <unknown>
#1 0x5613f420c8c6 <unknown>
#2 0x5613f4211e75 <unknown>
#3 0x5613f4213bce <unknown>
#4 0x5613f4213c5c <unknown>
#5 0x5613f4251ae2 <unknown>
#6 0x5613f42795a2 <unknown>
#7 0x5613f424be98 <unknown>
#8 0x5613f427976e <unknown>
#9 0x5613f4297c19 <unknown>
#10 0x5613f4279343 <unknown>
#11 0x5613f424a593 <unknown>
#12 0x5613f424af5e <unknown>
#13 0x5613f44da85b <unknown>
#14 0x5613f44de7b5 <unknown>
#15 0x5613f44c8581 <unknown>
#16 0x5613f44df342 <unknown>
#17 0x5613f44ad88f <unknown>
#18 0x5613f4505738 <unknown>
#19 0x5613f450590b <unknown>
#20 0x5613f45159c4 <unknown>
#21 0x7f80e9a1b3ec <unknown>

**Comment by simonfarah** [comment]
You most probably changed the tab in the driver or refreshed the page, mainly did something manually in the opened driver window. Is that right? If not, please upload some screenshots or video about the error you get.

**Comment by rexo6565** [comment]
ok its working now >>> when you adding followers ?

**Comment by rexo6565** [comment]
it works but that's the error i get afterwards its the same code
