### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by rexo6565** [simonfarah/tiktok-bot#112]
:
  File "/home/rexxxo/tiktok-bot/bot.py", line 205, in <module>
    bot.start()
  File "/home/rexxxo/tiktok-bot/bot.py", line 103, in start
    self.select_service(choice)
  File "/home/rexxxo/tiktok-bot/bot.py", line 115, in select_service
    self.start_service(div, video_url)
  File "/home/rexxxo/tiktok-bot/bot.py", line 139, in start_service
    remaining_time = self.check_remaining_time(div)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/tiktok-bot/bot.py", line 150, in check_remaining_time
    text = element.text
           ^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=123.0.6312.86); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5622e0d71873 <unknown>
#1 0x5622e0a678c6 <unknown>
#2 0x5622e0a6ce75 <unknown>
#3 0x5622e0a6ebce <unknown>
#4 0x5622e0a6ec5c <unknown>
#5 0x5622e0aacae2 <unknown>
#6 0x5622e0ad45a2 <unknown>
#7 0x5622e0aa6e98 <unknown>
#8 0x5622e0ad476e <unknown>
#9 0x5622e0af2c19 <unknown>
#10 0x5622e0ad4343 <unknown>
#11 0x5622e0aa5593 <unknown>
#12 0x5622e0aa5f5e <unknown>
#13 0x5622e0d3585b <unknown>
#14 0x5622e0d397b5 <unknown>
#15 0x5622e0d23581 <unknown>
#16 0x5622e0d3a342 <unknown>
#17 0x5622e0d0888f <unknown>
#18 0x5622e0d60738 <unknown>
#19 0x5622e0d6090b <unknown>
#20 0x5622e0d709c4 <unknown>
#21 0x7ff0e54553ec <unknown>

**Comment by rexo6565** [comment]
this the code for the shares i get after run a few times 
Traceback (most recent call last):
  File "/home/rexxxo/tiktok-bot/bot.py", line 205, in <module>
    bot.start()
  File "/home/rexxxo/tiktok-bot/bot.py", line 103, in start
    self.select_service(choice)
  File "/home/rexxxo/tiktok-bot/bot.py", line 115, in select_service
    self.start_service(div, video_url)
  File "/home/rexxxo/tiktok-bot/bot.py", line 132, in start_service
    WebDriverWait(self.driver, 5).until(
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 96, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/support/expected_conditions.py", line 364, in _predicate
    element = visibility_of(target)(driver)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/support/expected_conditions.py", line 173, in _predicate
    return _element_if_visible(element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/support/expected_conditions.py", line 179, in _element_if_visible
    return element if element.is_displayed() == visibility else False
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 252, in is_displayed
    return self.parent.execute_script(f"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);", self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/rexxxo/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=123.0.6312.86); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x560137233873 <unknown>
#1 0x560136f298c6 <unknown>
#2 0x560136f2ee75 <unknown>
#3 0x560136f30e88 <unknown>
#4 0x560136fb5c17 <unknown>
#5 0x560136f965a2 <unknown>
#6 0x560136fb4c19 <unknown>
#7 0x560136f96343 <unknown>
#8 0x560136f67593 <unknown>
#9 0x560136f67f5e <unknown>
#10 0x5601371f785b <unknown>
#11 0x5601371fb7b5 <unknown>
#12 0x5601371e5581 <unknown>
#13 0x5601371fc342 <unknown>
#14 0x5601371ca88f <unknown>
#15 0x560137222738 <unknown>
#16 0x56013722290b <unknown>
#17 0x5601372329c4 <unknown>
#18 0x7f22726b93ec <unknown>
