### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by eddylai** [simonfarah/tiktok-bot#126]
Traceback (most recent call last):
  File "C:\dev\tiktok-bot23\bot.py", line 205, in <module>
    bot.start()
  File "C:\dev\tiktok-bot23\bot.py", line 103, in start
    self.select_service(choice)
  File "C:\dev\tiktok-bot23\bot.py", line 115, in select_service
    self.start_service(div, video_url)
  File "C:\dev\tiktok-bot23\bot.py", line 132, in start_service
    WebDriverWait(self.driver, 5).until(
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\expected_conditions.py", line 356, in _predicate
    target = visibility_of(target)(driver)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\expected_conditions.py", line 169, in _predicate
    return _element_if_visible(element)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\expected_conditions.py", line 175, in _element_if_visible
    return element if element.is_displayed() == visibility else False
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webelement.py", line 252, in is_displayed
    return self.parent.execute_script(f"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);", self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 405, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
        GetHandleVerifier [0x00007FF7D361EEA2+31554]
        (No symbol) [0x00007FF7D3597ED9]
        (No symbol) [0x00007FF7D345872A]
        (No symbol) [0x00007FF7D345E55E]
        (No symbol) [0x00007FF7D34611D8]
        (No symbol) [0x00007FF7D34ED69B]
        (No symbol) [0x00007FF7D34CD02A]
        (No symbol) [0x00007FF7D34EC977]
        (No symbol) [0x00007FF7D34CCDD3]
        (No symbol) [0x00007FF7D349A33B]
        (No symbol) [0x00007FF7D349AED1]
        GetHandleVerifier [0x00007FF7D3928B1D+3217341]
        GetHandleVerifier [0x00007FF7D3975AE3+3532675]
        GetHandleVerifier [0x00007FF7D396B0E0+3489152]
        GetHandleVerifier [0x00007FF7D36CE776+750614]
        (No symbol) [0x00007FF7D35A375F]
        (No symbol) [0x00007FF7D359EB14]
        (No symbol) [0x00007FF7D359ECA2]
        (No symbol) [0x00007FF7D358E16F]
        BaseThreadInitThunk [0x00007FFEC477257D+29]
        RtlUserThreadStart [0x00007FFEC5D4AF28+40]

PS C:\dev\tiktok-bot23>

**Comment by tahaawan1** [comment]
Traceback (most recent call last):
File "C:\dev\tiktok-bot23\bot.py", line 205, in
bot.start()
File "C:\dev\tiktok-bot23\bot.py", line 103, in start
self.select_service(choice)
File "C:\dev\tiktok-bot23\bot.py", line 115, in select_service
self.start_service(div, video_url)
File "C:\dev\tiktok-bot23\bot.py", line 132, in start_service
WebDriverWait(self.driver, 5).until(
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\wait.py", line 86, in until
value = method(self._driver)
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\expected_conditions.py", line 356, in _predicate
target = visibility_of(target)(driver)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\expected_conditions.py", line 169, in _predicate
return _element_if_visible(element)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\expected_conditions.py", line 175, in _element_if_visible
return element if element.is_displayed() == visibility else False
^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webelement.py", line 252, in is_displayed
return self.parent.execute_script(f"/* isDisplayed */return ({isDisplayed_js}).apply(null, arguments);", self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 405, in execute_script
return self.execute(command, {"script": script, "args": converted_args})["value"]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
self.error_handler.check_response(response)
File "C:\Users\eddyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
(Session info: chrome=126.0.6478.127); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
GetHandleVerifier [0x00007FF7D361EEA2+31554]
(No symbol) [0x00007FF7D3597ED9]
(No symbol) [0x00007FF7D345872A]
(No symbol) [0x00007FF7D345E55E]
(No symbol) [0x00007FF7D34611D8]
(No symbol) [0x00007FF7D34ED69B]
(No symbol) [0x00007FF7D34CD02A]
(No symbol) [0x00007FF7D34EC977]
(No symbol) [0x00007FF7D34CCDD3]
(No symbol) [0x00007FF7D349A33B]
(No symbol) [0x00007FF7D349AED1]
GetHandleVerifier [0x00007FF7D3928B1D+3217341]
GetHandleVerifier [0x00007FF7D3975AE3+3532675]
GetHandleVerifier [0x00007FF7D396B0E0+3489152]
GetHandleVerifier [0x00007FF7D36CE776+750614]
(No symbol) [0x00007FF7D35A375F]
(No symbol) [0x00007FF7D359EB14]
(No symbol) [0x00007FF7D359ECA2]
(No symbol) [0x00007FF7D358E16F]
BaseThreadInitThunk [0x00007FFEC477257D+29]
RtlUserThreadStart [0x00007FFEC5D4AF28+40]

PS C:\dev\tiktok-bot23>

**Comment by simonfarah** [comment]
Can I please get a screen recording of the error being reproduced?

**Comment by simonfarah** [comment]
A new version has been pushed and should fix all raised bugs. Please try it and feel free to reopen an issue for any other bugs.
