### ISSUE TITLE
chrome driver is crashing

### ISSUE THREAD

**Issue by stannihart** [simonfarah/TikTok-Bot#39]
Traceback (most recent call last):
  File "/Users/stanni/repo/tBotTest/tiktok-bot.py", line 182, in <module>
    driver = webdriver.Chrome(PATH)
  File "/Users/stanni/repo/env/tBotTest/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Users/stanni/repo/env/tBotTest/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/Users/stanni/repo/env/tBotTest/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /Users/stanni/repo/tBotTest/chromedriver unexpectedly exited. Status code was: -9

**Comment by simonfarah** [comment]
Looks like you are running two instances of the chromedriver at the same time. You can't do that.
